### PR TITLE
SILA-2320: Created new form templates for each KYC Level and also integrated the Tips slider.

### PR DESCRIPTION
**Pull request by ArcGate-Vinod**
- Created new form templates for each `KYC Level` and also integrated the `Tips` slider.

Thanks!

### CODE REVIEW

**Comment by amack300** [comment]
LGTM, great work on creating separate components for each KYC flow and easily being able to swap them out.  Nice work!

**Comment by ArcGate-Vinod** [comment]
Hi @amack300,

Thanks for the quick updates and I appreciate your love in this PR, now in this branch, the development has been done. 
Please approve this PR.

Thanks!

**Review by amack300 — APPROVED** [review]
Hey @ArcGate-Vinod, I hope I did not step on any toes, but the tips carousel was built using a large chunk of custom CSS and I wanted to leverage bootstrap classes as much as possible.  I went ahead and made some code changes to the carousel but it should display pretty close to what it was before.  Approved!

**Comment by ArcGate-Vinod** [comment]
> Hey @ArcGate-Vinod, I hope I did not step on any toes, but the tips carousel was built using a large chunk of custom CSS and I wanted to leverage bootstrap classes as much as possible. I went ahead and made some code changes to the carousel but it should display pretty close to what it was before. Approved!

Hi @amack300,
Thanks for the UI fixes but I've pulled the changes and checked in local, while no `Carousel` when a single tip, the UI has broken which I've fixed and for your reference attached screen!

tips

Thanks!

**Pull request merged**
